name: "yolov5"
backend: "rknn"
max_batch_size : 1
input [
  {
    name: "images"
    data_type: TYPE_UINT8
    dims: [ 640, 640, 3 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, 85, 80, 80 ]
  },
  {
    name: "371"
    data_type: TYPE_FP32
    dims: [ 3, 85, 40, 40 ]
  },
  {
    name: "390"
    data_type: TYPE_FP32
    dims: [ 3, 85, 20, 20 ]
  }
]
instance_group [
  {
    count: 10
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
